project_name: unifi-access-mqtt
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: unifi-access-mqtt
    main: ./main.go
    binary: unifi-access-mqtt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "pharndt/unifi-access-mqtt:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    skip_push: false

  - image_templates:
      - "pharndt/unifi-access-mqtt:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    skip_push: false

docker_manifests:
  - id: tag
    name_template: "pharndt/unifi-access-mqtt:{{ .Tag }}"
    image_templates:
      - pharndt/unifi-access-mqtt:{{ .Tag }}-amd64
      - pharndt/unifi-access-mqtt:{{ .Tag }}-arm64

  - id: latest
    name_template: "pharndt/unifi-access-mqtt:latest"
    image_templates:
      - pharndt/unifi-access-mqtt:{{ .Tag }}-amd64
      - pharndt/unifi-access-mqtt:{{ .Tag }}-arm64

release:
  disable: false
  mode: replace
  draft: false
  prerelease: auto
  make_latest: true
  skip_upload: true
